---
name: Setup environment
description: Setup Node.js, with npm cache, install dependencies

runs:
  using: 'composite'
  steps:
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci
